SELECT *
FROM (SELECT ROWNUM RNUM, BOARD_NUM, BOARD_TITLE, 
      BOARD_WRITER, BOARD_CONTENT, BOARD_DATE, BOARD_READCOUNT, 
      ORIGINAL_FILENAME, RENAME_FILENAME, BOARD_REF, BOARD_LEV, BOARD_SEQ
      FROM (SELECT * FROM BOARD
      WHERE BOARD_DELETE_YN = 'N'
      ORDER BY BOARD_REF DESC, BOARD_SEQ ASC))
WHERE RNUM >= 1 AND RNUM <= 10;

--¸ñ·ÏÀÇ ÃÑ °¹¼ö Á¶È¸
SELECT COUNT(*) FROM BOARD
WHERE BOARD_DELETE_YN = 'N';