drop table notice;

CREATE TABLE NOTICE(
  NOTICE_NO   NUMBER,
  NOTICE_TITLE VARCHAR2(100) NOT NULL,
  NOTICE_WRITER VARCHAR2(20) NOT NULL,
  NOTICE_DATE DATE DEFAULT SYSDATE,
  NOTICE_CONTENT VARCHAR2(2000),
  CONSTRAINT PK_NOTICE PRIMARY KEY (NOTICE_NO),
  CONSTRAINT FK_NWRITER FOREIGN KEY (NOTICE_WRITER) REFERENCES MEMBER (USERID)
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '글번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '글제목';
COMMENT ON COLUMN NOTICE.NOTICE_WRITER IS '작성자아이디';
COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '작성날짜';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '글내용';

CREATE SEQUENCE SEQ_NOTICENO
NOCACHE;

INSERT INTO NOTICE VALUES (SEQ_NOTICENO.NEXTVAL, '관리자 공지1', 'admin', DEFAULT, '반갑습니다. 저희 서비스를 이용해 주셔서 감사합니다.');
INSERT INTO NOTICE VALUES (SEQ_NOTICENO.NEXTVAL, '서비스 개시 환영', 'user01', DEFAULT, '서비스가 개시되어 좋아요. 방가방가^^');
INSERT INTO NOTICE VALUES (SEQ_NOTICENO.NEXTVAL, '미투', 'user02', DEFAULT, '방가방가^^*. 앞으로 좋은 내용 개시 기대합니다.');

SELECT * FROM NOTICE;

COMMIT;









