/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-03-08 04:01:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class memberDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/view/member/../../menu.jsp", Long.valueOf(1457404845233L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1457310158874L));
    _jspx_dependants.put("jar:file:/E:/오전반_수업자료/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/firstWebProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Member m = (Member)request.getAttribute("member");

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>내 정보 보기</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>menu</title>\r\n");
      out.write("\r\n");
      out.write("<style>\t\r\n");
      out.write("\theader { width: 100%; height: 150px; background: #d0d52f; }\r\n");
      out.write("\theader ul li { float: left; width: 200px; height: 40px; background: #ff8204;\r\n");
      out.write("\t\t\tborder-radius: 10px; margin-right: 10px; padding-top: 5px;\r\n");
      out.write("\t\t\ttext-align: center;}\r\n");
      out.write("\theader ul li a { text-decoration: none; display: block; font-size: 20pt;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\t<h1 align=\"center\">");
      out.print( m.getUserName() );
      out.write(" 님의 정보는 다음과 같습니다.</h1>\r\n");
      out.write("\t<form action=\"/first/mupdate\" method=\"post\">\r\n");
      out.write("\t<table align=\"center\" width=\"600\" cellspacing=\"0\" border=\"1\" cellpadding=\"5\">\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"hidden\" name=\"username\" value=\"");
      out.print( m.getUserName() );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"userid\" value=\"");
      out.print( m.getUserId() );
      out.write("\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<tr><td bgcolor=\"#8edbff\" width=\"200\">이 름</td>\r\n");
      out.write("\t\t   <td><input type=\"text\" name=\"username\" value=\"");
      out.print( m.getUserName() );
      out.write("\" readonly></td></tr>\r\n");
      out.write("\t\t<tr><td bgcolor=\"#8edbff\">아이디</td>\r\n");
      out.write("\t\t   <td><input type=\"text\" name=\"userid\" id=\"userid\" value=\"");
      out.print( m.getUserId() );
      out.write("\" readonly> &nbsp; \r\n");
      out.write("\t\t       </td></tr>\r\n");
      out.write("\t\t<tr><td bgcolor=\"#8edbff\">암 호</td>\r\n");
      out.write("\t\t   <td><input type=\"password\" name=\"userpwd\" id=\"userpwd1\" value=\"");
      out.print( m.getUserPwd() );
      out.write("\"></td></tr>\r\n");
      out.write("\t\t<tr><td bgcolor=\"#8edbff\">암호 확인</td>\r\n");
      out.write("\t\t   <td><input type=\"password\" id=\"userpwd2\"></td></tr>\r\n");
      out.write("\t\t<tr><td bgcolor=\"#8edbff\">이메일</td>\r\n");
      out.write("\t\t    <td><input type=\"email\" name=\"email\" value=\"");
      out.print( m.getEmail() );
      out.write("\"></td></tr>\r\n");
      out.write("\t\t<tr><td bgcolor=\"#8edbff\">성 별</td>\r\n");
      out.write("\t\t   <td>\r\n");
      out.write("\t\t   ");
 if(m.getGender().equals("M")){ 
      out.write("\r\n");
      out.write("\t\t   \t   <input type=\"radio\" name=\"gender\" value=\"M\" checked> 남 &nbsp;\r\n");
      out.write("\t\t       <input type=\"radio\" name=\"gender\" value=\"F\"> 여 \r\n");
      out.write("\t\t   ");
 } 
		    	if(m.getGender().equals("F")){ 
      out.write("\r\n");
      out.write("\t\t   \t   <input type=\"radio\" name=\"gender\" value=\"M\" > 남 &nbsp;\r\n");
      out.write("\t\t       <input type=\"radio\" name=\"gender\" value=\"F\" checked> 여 \r\n");
      out.write("\t\t   ");
 } 
      out.write(" \r\n");
      out.write("\t\t    </td></tr>\r\n");
      out.write("\t\t<tr><td bgcolor=\"#8edbff\">생 일</td>\r\n");
      out.write("\t\t\t<td><input type=\"date\" name=\"birth\" value=\"");
      out.print( m.getBirth() );
      out.write("\"></td></tr>\r\n");
      out.write("\t\t<tr><td bgcolor=\"#8edbff\">전화번호</td>\r\n");
      out.write("\t\t   <td><input type=\"tel\" name=\"phone\" value=\"");
      out.print( m.getPhone() );
      out.write("\"></td></tr>\r\n");
      out.write("\t\t<tr><td bgcolor=\"#8edbff\">주 소</td>\r\n");
      out.write("\t\t");

			String zcode1 = m.getAddress().substring(0, 3);
			String zcode2 = m.getAddress().substring(4, 7);
			String address = m.getAddress().substring(7);
		
      out.write("\r\n");
      out.write("\t\t   <td>\r\n");
      out.write("\t\t   우편번호 : <input type=\"text\" size=\"5\" maxlength=\"3\" name=\"zcode1\" value=\"");
      out.print( zcode1 );
      out.write("\">\r\n");
      out.write("\t\t   - <input type=\"text\" size=\"5\" maxlength=\"3\" name=\"zcode2\" value=\"");
      out.print( zcode2 );
      out.write("\"> &nbsp; \r\n");
      out.write("\t\t   <button>우편번호검색</button><br>\r\n");
      out.write("\t\t   <input type=\"text\" name=\"address\" size=\"40\" value=\"");
      out.print( address );
      out.write("\">\r\n");
      out.write("\t\t   </td></tr>\r\n");
      out.write("\t\t<tr><td bgcolor=\"#8edbff\">취 미</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t");

			String[] checkedItem = new String[9];
			String[] values = m.getHobby().split(",");
			for(int i = 0; i < values.length; i++){
				if(values[i].equals("등산"))
					checkedItem[0] = "checked";
				if(values[i].equals("운동"))
					checkedItem[1] = "checked";
				if(values[i].equals("댄스스포츠"))
					checkedItem[2] = "checked";
				if(values[i].equals("여행"))
					checkedItem[3] = "checked";
				if(values[i].equals("독서"))
					checkedItem[4] = "checked";
				if(values[i].equals("영화감상"))
					checkedItem[5] = "checked";
				if(values[i].equals("음악듣기"))
					checkedItem[6] = "checked";
				if(values[i].equals("요리"))
					checkedItem[7] = "checked";
				if(values[i].equals("기타"))
					checkedItem[8] = "checked";
			}
		
      out.write("\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr><td><input type=\"checkbox\" name=\"hobby\" value=\"등산\" ");
      out.print( checkedItem[0] );
      out.write("> 등산</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"hobby\" value=\"운동\" ");
      out.print( checkedItem[1] );
      out.write("> 운동</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"hobby\" value=\"댄스스포츠\" ");
      out.print( checkedItem[2] );
      out.write("> 댄스스포츠</td></tr>\r\n");
      out.write("\t\t\t\t<tr><td><input type=\"checkbox\" name=\"hobby\" value=\"여행\" ");
      out.print( checkedItem[3] );
      out.write("> 여행</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"hobby\" value=\"독서\" ");
      out.print( checkedItem[4] );
      out.write("> 독서</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"hobby\" value=\"영화감상\" ");
      out.print( checkedItem[5] );
      out.write("> 영화감상</td></tr>\r\n");
      out.write("\t\t\t\t<tr><td><input type=\"checkbox\" name=\"hobby\" value=\"음악듣기\" ");
      out.print( checkedItem[6] );
      out.write("> 음악듣기</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"hobby\" value=\"요리\" ");
      out.print( checkedItem[7] );
      out.write("> 요리</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"hobby\" value=\"기타\" ");
      out.print( checkedItem[8] );
      out.write("> 기타</td></tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td></tr>\r\n");
      out.write("\t\t<tr><td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"수정하기\"> &nbsp; \r\n");
      out.write("\t\t\t<a href=\"/first/mdelete?userid=");
      out.print( m.getUserId() );
      out.write("\">탈퇴하기</a>\r\n");
      out.write("\t\t</td></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /view/member/../../menu.jsp(24,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t<header id=\"notLogin\">\r\n");
        out.write("\t<h1 style=\"font-size:40px;font-weight:bold;\">Welcome First Web!!</h1>\r\n");
        out.write("\t\t<ul style=\"list-style:none\">\r\n");
        out.write("\t\t\t<li><a href=\"/first/index.jsp\">home</a></li>\r\n");
        out.write("\t\t\t<li><a href=\"/first/nlist\">공지사항</a></li>\r\n");
        out.write("\t\t\t<li><a>게시글</a></li>\r\n");
        out.write("\t\t</ul>\r\n");
        out.write("\t</header>\r\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /view/member/../../menu.jsp(35,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t<header id=\"login\">\r\n");
        out.write("\t<h1 style=\"font-size:40px;\">Welcome First Web!!</h1>\r\n");
        out.write("\t\t<ul style=\"list-style:none\">\r\n");
        out.write("\t\t\t<li><a href=\"/first/index.jsp\">home</a></li>\r\n");
        out.write("\t\t\t<li><a href=\"/first/nlist\">공지사항</a></li>\r\n");
        out.write("\t\t\t<li><a>게시글</a></li>\r\n");
        out.write("\t\t\t<li><a href=\"/first/mdetail?userid=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">내정보보기</a></li>\r\n");
        out.write("\t\t\t<li><a href=\"/first/logout\" target=\"_top\">로그아웃</a></li>\r\n");
        out.write("\t\t</ul>\r\n");
        out.write("\t</header>\r\n");
        out.write('\r');
        out.write('\n');
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
